# TODO port to environment variable
@BASE_DOMAIN=http://localhost:8080
@BASE_URL={{BASE_DOMAIN}}/weather-summary

# happy cases

# city, Berlin
GET {{BASE_URL}}?location=52.5243,13.4105
User-Agent: rest-client
Content-Type: application/json

###

# town, Saltsjobaden
GET {{BASE_URL}}?location=59.2833,18.3
User-Agent: rest-client
Content-Type: application/json

###

# municipality, Nacka
GET {{BASE_URL}}?location=59.3105,18.1637
User-Agent: rest-client
Content-Type: application/json

###
# no decimals in latlon query param
GET {{BASE_URL}}?location=59,18
User-Agent: rest-client
Content-Type: application/json

###
# gazillion decimals
GET {{BASE_URL}}?location=59.324234243242342,18.467458476869
User-Agent: rest-client
Content-Type: application/json

###
# latitude,longitude out of range
GET {{BASE_URL}}?location=593,183
User-Agent: rest-client
Content-Type: application/json

###
# trailing decimal point, but no following decimals
# TODO this should be valid input, but currently fails validation
GET {{BASE_URL}}?location=59.,18.
User-Agent: rest-client
Content-Type: application/json

###

# exceptional input

# invalid path
GET {{BASE_DOMAIN}}
User-Agent: rest-client
Content-Type: application/json

###

# no location supplied
GET {{BASE_URL}}
User-Agent: rest-client
Content-Type: application/json

###

# empty location
GET {{BASE_URL}}?location=
User-Agent: rest-client
Content-Type: application/json

###

# location does not exist
GET {{BASE_URL}}?location=9999999,999999
User-Agent: rest-client
Content-Type: application/json

###

# wrong format
GET {{BASE_URL}}?location=59.2833
User-Agent: rest-client
Content-Type: application/json

###

# try injection: panic("WELP")
GET {{BASE_URL}}?location=panic%28%22WELP%22%29
User-Agent: rest-client
Content-Type: application/json

###
